// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: internal/gateway/grpc/protos/cart.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_cart_proto_rawDescGZIP(), []int{0}
}

func (x *GetCartRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_cart_proto_rawDescGZIP(), []int{1}
}

func (x *AddToCartRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddToCartRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddToCartGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Request       *AddToCartRequest      `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartGrpcRequest) Reset() {
	*x = AddToCartGrpcRequest{}
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartGrpcRequest) ProtoMessage() {}

func (x *AddToCartGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartGrpcRequest.ProtoReflect.Descriptor instead.
func (*AddToCartGrpcRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_cart_proto_rawDescGZIP(), []int{2}
}

func (x *AddToCartGrpcRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddToCartGrpcRequest) GetRequest() *AddToCartRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type UpdateCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      int32                  `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemRequest) Reset() {
	*x = UpdateCartItemRequest{}
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemRequest) ProtoMessage() {}

func (x *UpdateCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_cart_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCartItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateCartItemGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        uint64                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Request       *UpdateCartItemRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemGrpcRequest) Reset() {
	*x = UpdateCartItemGrpcRequest{}
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemGrpcRequest) ProtoMessage() {}

func (x *UpdateCartItemGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemGrpcRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartItemGrpcRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_cart_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCartItemGrpcRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCartItemGrpcRequest) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UpdateCartItemGrpcRequest) GetRequest() *UpdateCartItemRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type RemoveFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        uint64                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartRequest) Reset() {
	*x = RemoveFromCartRequest{}
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartRequest) ProtoMessage() {}

func (x *RemoveFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromCartRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_cart_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveFromCartRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveFromCartRequest) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CartItems     []*CartItemResponse    `protobuf:"bytes,3,rep,name=cart_items,json=cartItems,proto3" json:"cart_items,omitempty"`
	Total         float64                `protobuf:"fixed64,4,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_cart_proto_rawDescGZIP(), []int{6}
}

func (x *CartResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartResponse) GetCartItems() []*CartItemResponse {
	if x != nil {
		return x.CartItems
	}
	return nil
}

func (x *CartResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CartResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CartResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Product       *ProductResponse       `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Subtotal      float64                `protobuf:"fixed64,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemResponse) Reset() {
	*x = CartItemResponse{}
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemResponse) ProtoMessage() {}

func (x *CartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemResponse.ProtoReflect.Descriptor instead.
func (*CartItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_cart_proto_rawDescGZIP(), []int{7}
}

func (x *CartItemResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItemResponse) GetProduct() *ProductResponse {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *CartItemResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItemResponse) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *CartItemResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CartItemResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_internal_gateway_grpc_protos_cart_proto protoreflect.FileDescriptor

const file_internal_gateway_grpc_protos_cart_proto_rawDesc = "" +
	"\n" +
	"'internal/gateway/grpc/protos/cart.proto\x12\x06protos\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a*internal/gateway/grpc/protos/product.proto\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"M\n" +
	"\x10AddToCartRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"c\n" +
	"\x14AddToCartGrpcRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x122\n" +
	"\arequest\x18\x02 \x01(\v2\x18.protos.AddToCartRequestR\arequest\"3\n" +
	"\x15UpdateCartItemRequest\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\x05R\bquantity\"\x86\x01\n" +
	"\x19UpdateCartItemGrpcRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x04R\x06itemId\x127\n" +
	"\arequest\x18\x03 \x01(\v2\x1d.protos.UpdateCartItemRequestR\arequest\"I\n" +
	"\x15RemoveFromCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x04R\x06itemId\"\xfc\x01\n" +
	"\fCartResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x127\n" +
	"\n" +
	"cart_items\x18\x03 \x03(\v2\x18.protos.CartItemResponseR\tcartItems\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x01R\x05total\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x83\x02\n" +
	"\x10CartItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x121\n" +
	"\aproduct\x18\x02 \x01(\v2\x17.protos.ProductResponseR\aproduct\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1a\n" +
	"\bsubtotal\x18\x04 \x01(\x01R\bsubtotal\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\x9b\x02\n" +
	"\vCartService\x127\n" +
	"\aGetCart\x12\x16.protos.GetCartRequest\x1a\x14.protos.CartResponse\x12?\n" +
	"\tAddToCart\x12\x1c.protos.AddToCartGrpcRequest\x1a\x14.protos.CartResponse\x12I\n" +
	"\x0eUpdateCartItem\x12!.protos.UpdateCartItemGrpcRequest\x1a\x14.protos.CartResponse\x12G\n" +
	"\x0eRemoveFromCart\x12\x1d.protos.RemoveFromCartRequest\x1a\x16.google.protobuf.EmptyBHZFgithub.com/saleh-ghazimoradi/GopherMarket/internal/gateway/grpc/protosb\x06proto3"

var (
	file_internal_gateway_grpc_protos_cart_proto_rawDescOnce sync.Once
	file_internal_gateway_grpc_protos_cart_proto_rawDescData []byte
)

func file_internal_gateway_grpc_protos_cart_proto_rawDescGZIP() []byte {
	file_internal_gateway_grpc_protos_cart_proto_rawDescOnce.Do(func() {
		file_internal_gateway_grpc_protos_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_gateway_grpc_protos_cart_proto_rawDesc), len(file_internal_gateway_grpc_protos_cart_proto_rawDesc)))
	})
	return file_internal_gateway_grpc_protos_cart_proto_rawDescData
}

var file_internal_gateway_grpc_protos_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_gateway_grpc_protos_cart_proto_goTypes = []any{
	(*GetCartRequest)(nil),            // 0: protos.GetCartRequest
	(*AddToCartRequest)(nil),          // 1: protos.AddToCartRequest
	(*AddToCartGrpcRequest)(nil),      // 2: protos.AddToCartGrpcRequest
	(*UpdateCartItemRequest)(nil),     // 3: protos.UpdateCartItemRequest
	(*UpdateCartItemGrpcRequest)(nil), // 4: protos.UpdateCartItemGrpcRequest
	(*RemoveFromCartRequest)(nil),     // 5: protos.RemoveFromCartRequest
	(*CartResponse)(nil),              // 6: protos.CartResponse
	(*CartItemResponse)(nil),          // 7: protos.CartItemResponse
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
	(*ProductResponse)(nil),           // 9: protos.ProductResponse
	(*emptypb.Empty)(nil),             // 10: google.protobuf.Empty
}
var file_internal_gateway_grpc_protos_cart_proto_depIdxs = []int32{
	1,  // 0: protos.AddToCartGrpcRequest.request:type_name -> protos.AddToCartRequest
	3,  // 1: protos.UpdateCartItemGrpcRequest.request:type_name -> protos.UpdateCartItemRequest
	7,  // 2: protos.CartResponse.cart_items:type_name -> protos.CartItemResponse
	8,  // 3: protos.CartResponse.created_at:type_name -> google.protobuf.Timestamp
	8,  // 4: protos.CartResponse.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 5: protos.CartItemResponse.product:type_name -> protos.ProductResponse
	8,  // 6: protos.CartItemResponse.created_at:type_name -> google.protobuf.Timestamp
	8,  // 7: protos.CartItemResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: protos.CartService.GetCart:input_type -> protos.GetCartRequest
	2,  // 9: protos.CartService.AddToCart:input_type -> protos.AddToCartGrpcRequest
	4,  // 10: protos.CartService.UpdateCartItem:input_type -> protos.UpdateCartItemGrpcRequest
	5,  // 11: protos.CartService.RemoveFromCart:input_type -> protos.RemoveFromCartRequest
	6,  // 12: protos.CartService.GetCart:output_type -> protos.CartResponse
	6,  // 13: protos.CartService.AddToCart:output_type -> protos.CartResponse
	6,  // 14: protos.CartService.UpdateCartItem:output_type -> protos.CartResponse
	10, // 15: protos.CartService.RemoveFromCart:output_type -> google.protobuf.Empty
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_gateway_grpc_protos_cart_proto_init() }
func file_internal_gateway_grpc_protos_cart_proto_init() {
	if File_internal_gateway_grpc_protos_cart_proto != nil {
		return
	}
	file_internal_gateway_grpc_protos_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_gateway_grpc_protos_cart_proto_rawDesc), len(file_internal_gateway_grpc_protos_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_gateway_grpc_protos_cart_proto_goTypes,
		DependencyIndexes: file_internal_gateway_grpc_protos_cart_proto_depIdxs,
		MessageInfos:      file_internal_gateway_grpc_protos_cart_proto_msgTypes,
	}.Build()
	File_internal_gateway_grpc_protos_cart_proto = out.File
	file_internal_gateway_grpc_protos_cart_proto_goTypes = nil
	file_internal_gateway_grpc_protos_cart_proto_depIdxs = nil
}
