// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: internal/gateway/grpc/protos/product.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaginatedMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedMeta) Reset() {
	*x = PaginatedMeta{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedMeta) ProtoMessage() {}

func (x *PaginatedMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedMeta.ProtoReflect.Descriptor instead.
func (*PaginatedMeta) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{0}
}

func (x *PaginatedMeta) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginatedMeta) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginatedMeta) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginatedMeta) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type ProductImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	AltText       string                 `protobuf:"bytes,3,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductImageResponse) Reset() {
	*x = ProductImageResponse{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductImageResponse) ProtoMessage() {}

func (x *ProductImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductImageResponse.ProtoReflect.Descriptor instead.
func (*ProductImageResponse) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductImageResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductImageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProductImageResponse) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *ProductImageResponse) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *ProductImageResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ProductResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    uint64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                   `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Sku           string                  `protobuf:"bytes,7,opt,name=sku,proto3" json:"sku,omitempty"`
	IsActive      bool                    `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Category      *CategoryResponse       `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	Images        []*ProductImageResponse `protobuf:"bytes,10,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductResponse) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProductResponse) GetCategory() *CategoryResponse {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *ProductResponse) GetImages() []*ProductImageResponse {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProductSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductResponse       `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Rank          float32                `protobuf:"fixed32,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSearchResult) Reset() {
	*x = ProductSearchResult{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSearchResult) ProtoMessage() {}

func (x *ProductSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSearchResult.ProtoReflect.Descriptor instead.
func (*ProductSearchResult) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductSearchResult) GetProduct() *ProductResponse {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *ProductSearchResult) GetRank() float32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    uint64                 `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Sku           string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProductRequest) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductResponse     `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Meta          *PaginatedMeta         `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsResponse) GetProducts() []*ProductResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetMeta() *PaginatedMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    *uint64                `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Price         *float64               `protobuf:"fixed64,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Stock         *int32                 `protobuf:"varint,6,opt,name=stock,proto3,oneof" json:"stock,omitempty"`
	IsActive      *bool                  `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetCategoryId() uint64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetStock() int32 {
	if x != nil && x.Stock != nil {
		return *x.Stock
	}
	return 0
}

func (x *UpdateProductRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddProductImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	AltText       string                 `protobuf:"bytes,3,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductImageRequest) Reset() {
	*x = AddProductImageRequest{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductImageRequest) ProtoMessage() {}

func (x *AddProductImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductImageRequest.ProtoReflect.Descriptor instead.
func (*AddProductImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{10}
}

func (x *AddProductImageRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddProductImageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddProductImageRequest) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	CategoryId    *uint64                `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	MinPrice      *float64               `protobuf:"fixed64,5,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *float64               `protobuf:"fixed64,6,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{11}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchProductsRequest) GetCategoryId() uint64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *SearchProductsRequest) GetMinPrice() float64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *SearchProductsRequest) GetMaxPrice() float64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

type SearchProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ProductSearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Meta          *PaginatedMeta         `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResponse) Reset() {
	*x = SearchProductsResponse{}
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResponse) ProtoMessage() {}

func (x *SearchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gateway_grpc_protos_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResponse.ProtoReflect.Descriptor instead.
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return file_internal_gateway_grpc_protos_product_proto_rawDescGZIP(), []int{12}
}

func (x *SearchProductsResponse) GetResults() []*ProductSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchProductsResponse) GetMeta() *PaginatedMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_internal_gateway_grpc_protos_product_proto protoreflect.FileDescriptor

const file_internal_gateway_grpc_protos_product_proto_rawDesc = "" +
	"\n" +
	"*internal/gateway/grpc/protos/product.proto\x12\x06protos\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a+internal/gateway/grpc/protos/category.proto\"p\n" +
	"\rPaginatedMeta\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xad\x01\n" +
	"\x14ProductImageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x19\n" +
	"\balt_text\x18\x03 \x01(\tR\aaltText\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb5\x03\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x04R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12\x10\n" +
	"\x03sku\x18\a \x01(\tR\x03sku\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x124\n" +
	"\bcategory\x18\t \x01(\v2\x18.protos.CategoryResponseR\bcategory\x124\n" +
	"\x06images\x18\n" +
	" \x03(\v2\x1c.protos.ProductImageResponseR\x06images\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\\\n" +
	"\x13ProductSearchResult\x121\n" +
	"\aproduct\x18\x01 \x01(\v2\x17.protos.ProductResponseR\aproduct\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x02R\x04rank\"\xab\x01\n" +
	"\x14CreateProductRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x04R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\"?\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"v\n" +
	"\x14ListProductsResponse\x123\n" +
	"\bproducts\x18\x01 \x03(\v2\x17.protos.ProductResponseR\bproducts\x12)\n" +
	"\x04meta\x18\x02 \x01(\v2\x15.protos.PaginatedMetaR\x04meta\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xaf\x02\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\x04H\x00R\n" +
	"categoryId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x05 \x01(\x01H\x03R\x05price\x88\x01\x01\x12\x19\n" +
	"\x05stock\x18\x06 \x01(\x05H\x04R\x05stock\x88\x01\x01\x12 \n" +
	"\tis_active\x18\a \x01(\bH\x05R\bisActive\x88\x01\x01B\x0e\n" +
	"\f_category_idB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_priceB\b\n" +
	"\x06_stockB\f\n" +
	"\n" +
	"_is_active\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"d\n" +
	"\x16AddProductImageRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x19\n" +
	"\balt_text\x18\x03 \x01(\tR\aaltText\"\xed\x01\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12$\n" +
	"\vcategory_id\x18\x04 \x01(\x04H\x00R\n" +
	"categoryId\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x05 \x01(\x01H\x01R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\x06 \x01(\x01H\x02R\bmaxPrice\x88\x01\x01B\x0e\n" +
	"\f_category_idB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_price\"z\n" +
	"\x16SearchProductsResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.protos.ProductSearchResultR\aresults\x12)\n" +
	"\x04meta\x18\x02 \x01(\v2\x15.protos.PaginatedMetaR\x04meta2\x96\x04\n" +
	"\x0eProductService\x12F\n" +
	"\rCreateProduct\x12\x1c.protos.CreateProductRequest\x1a\x17.protos.ProductResponse\x12I\n" +
	"\fListProducts\x12\x1b.protos.ListProductsRequest\x1a\x1c.protos.ListProductsResponse\x12@\n" +
	"\n" +
	"GetProduct\x12\x19.protos.GetProductRequest\x1a\x17.protos.ProductResponse\x12F\n" +
	"\rUpdateProduct\x12\x1c.protos.UpdateProductRequest\x1a\x17.protos.ProductResponse\x12E\n" +
	"\rDeleteProduct\x12\x1c.protos.DeleteProductRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x0fAddProductImage\x12\x1e.protos.AddProductImageRequest\x1a\x1c.protos.ProductImageResponse\x12O\n" +
	"\x0eSearchProducts\x12\x1d.protos.SearchProductsRequest\x1a\x1e.protos.SearchProductsResponseBHZFgithub.com/saleh-ghazimoradi/GopherMarket/internal/gateway/grpc/protosb\x06proto3"

var (
	file_internal_gateway_grpc_protos_product_proto_rawDescOnce sync.Once
	file_internal_gateway_grpc_protos_product_proto_rawDescData []byte
)

func file_internal_gateway_grpc_protos_product_proto_rawDescGZIP() []byte {
	file_internal_gateway_grpc_protos_product_proto_rawDescOnce.Do(func() {
		file_internal_gateway_grpc_protos_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_gateway_grpc_protos_product_proto_rawDesc), len(file_internal_gateway_grpc_protos_product_proto_rawDesc)))
	})
	return file_internal_gateway_grpc_protos_product_proto_rawDescData
}

var file_internal_gateway_grpc_protos_product_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_gateway_grpc_protos_product_proto_goTypes = []any{
	(*PaginatedMeta)(nil),          // 0: protos.PaginatedMeta
	(*ProductImageResponse)(nil),   // 1: protos.ProductImageResponse
	(*ProductResponse)(nil),        // 2: protos.ProductResponse
	(*ProductSearchResult)(nil),    // 3: protos.ProductSearchResult
	(*CreateProductRequest)(nil),   // 4: protos.CreateProductRequest
	(*ListProductsRequest)(nil),    // 5: protos.ListProductsRequest
	(*ListProductsResponse)(nil),   // 6: protos.ListProductsResponse
	(*GetProductRequest)(nil),      // 7: protos.GetProductRequest
	(*UpdateProductRequest)(nil),   // 8: protos.UpdateProductRequest
	(*DeleteProductRequest)(nil),   // 9: protos.DeleteProductRequest
	(*AddProductImageRequest)(nil), // 10: protos.AddProductImageRequest
	(*SearchProductsRequest)(nil),  // 11: protos.SearchProductsRequest
	(*SearchProductsResponse)(nil), // 12: protos.SearchProductsResponse
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
	(*CategoryResponse)(nil),       // 14: protos.CategoryResponse
	(*emptypb.Empty)(nil),          // 15: google.protobuf.Empty
}
var file_internal_gateway_grpc_protos_product_proto_depIdxs = []int32{
	13, // 0: protos.ProductImageResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: protos.ProductResponse.category:type_name -> protos.CategoryResponse
	1,  // 2: protos.ProductResponse.images:type_name -> protos.ProductImageResponse
	13, // 3: protos.ProductResponse.created_at:type_name -> google.protobuf.Timestamp
	13, // 4: protos.ProductResponse.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: protos.ProductSearchResult.product:type_name -> protos.ProductResponse
	2,  // 6: protos.ListProductsResponse.products:type_name -> protos.ProductResponse
	0,  // 7: protos.ListProductsResponse.meta:type_name -> protos.PaginatedMeta
	3,  // 8: protos.SearchProductsResponse.results:type_name -> protos.ProductSearchResult
	0,  // 9: protos.SearchProductsResponse.meta:type_name -> protos.PaginatedMeta
	4,  // 10: protos.ProductService.CreateProduct:input_type -> protos.CreateProductRequest
	5,  // 11: protos.ProductService.ListProducts:input_type -> protos.ListProductsRequest
	7,  // 12: protos.ProductService.GetProduct:input_type -> protos.GetProductRequest
	8,  // 13: protos.ProductService.UpdateProduct:input_type -> protos.UpdateProductRequest
	9,  // 14: protos.ProductService.DeleteProduct:input_type -> protos.DeleteProductRequest
	10, // 15: protos.ProductService.AddProductImage:input_type -> protos.AddProductImageRequest
	11, // 16: protos.ProductService.SearchProducts:input_type -> protos.SearchProductsRequest
	2,  // 17: protos.ProductService.CreateProduct:output_type -> protos.ProductResponse
	6,  // 18: protos.ProductService.ListProducts:output_type -> protos.ListProductsResponse
	2,  // 19: protos.ProductService.GetProduct:output_type -> protos.ProductResponse
	2,  // 20: protos.ProductService.UpdateProduct:output_type -> protos.ProductResponse
	15, // 21: protos.ProductService.DeleteProduct:output_type -> google.protobuf.Empty
	1,  // 22: protos.ProductService.AddProductImage:output_type -> protos.ProductImageResponse
	12, // 23: protos.ProductService.SearchProducts:output_type -> protos.SearchProductsResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_gateway_grpc_protos_product_proto_init() }
func file_internal_gateway_grpc_protos_product_proto_init() {
	if File_internal_gateway_grpc_protos_product_proto != nil {
		return
	}
	file_internal_gateway_grpc_protos_category_proto_init()
	file_internal_gateway_grpc_protos_product_proto_msgTypes[8].OneofWrappers = []any{}
	file_internal_gateway_grpc_protos_product_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_gateway_grpc_protos_product_proto_rawDesc), len(file_internal_gateway_grpc_protos_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_gateway_grpc_protos_product_proto_goTypes,
		DependencyIndexes: file_internal_gateway_grpc_protos_product_proto_depIdxs,
		MessageInfos:      file_internal_gateway_grpc_protos_product_proto_msgTypes,
	}.Build()
	File_internal_gateway_grpc_protos_product_proto = out.File
	file_internal_gateway_grpc_protos_product_proto_goTypes = nil
	file_internal_gateway_grpc_protos_product_proto_depIdxs = nil
}
