package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/saleh-ghazimoradi/GopherMarket/internal/dto"
	"github.com/saleh-ghazimoradi/GopherMarket/internal/gateway/graph"
	"github.com/saleh-ghazimoradi/GopherMarket/internal/gateway/graph/model"
	"github.com/saleh-ghazimoradi/GopherMarket/internal/gateway/middleware"
	"github.com/saleh-ghazimoradi/GopherMarket/internal/helper"
	"github.com/saleh-ghazimoradi/GopherMarket/utils"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input dto.RegisterRequest) (*dto.AuthResponse, error) {
	v := helper.NewValidator()
	dto.ValidateRegisterRequest(v, &input)
	if !v.Valid() {
		return nil, helper.NewValidateError(v)
	}

	authResp, refreshToken, err := r.authService.Register(ctx, &input)
	if err != nil {
		return nil, fmt.Errorf("register error: %w", err)
	}

	// Set the cookie
	if w, ok := ctx.Value(middleware.HTTPResponseKey).(http.ResponseWriter); ok {
		r.setRefreshTokenCookie(w, refreshToken)
	}
	return authResp, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input dto.LoginRequest) (*dto.AuthResponse, error) {
	v := helper.NewValidator()
	dto.ValidateLoginRequest(v, &input)
	if !v.Valid() {
		return nil, helper.NewValidateError(v)
	}

	authResp, refreshToken, err := r.authService.Login(ctx, &input)
	if err != nil {
		return nil, fmt.Errorf("login error: %w", err)
	}

	if w, ok := ctx.Value(middleware.HTTPResponseKey).(http.ResponseWriter); ok {
		r.setRefreshTokenCookie(w, refreshToken)
	}
	return authResp, nil
}

// GoogleLogin is the resolver for the googleLogin field.
func (r *mutationResolver) GoogleLogin(ctx context.Context, input dto.GoogleLoginRequest) (*dto.AuthResponse, error) {
	v := helper.NewValidator()
	dto.ValidateGoogleLoginRequest(v, &input)
	if !v.Valid() {
		return nil, helper.NewValidateError(v)
	}

	authResp, refreshToken, err := r.authService.GoogleLogin(ctx, &input)
	if err != nil {
		return nil, fmt.Errorf("google oauth login error: %w", err)
	}

	if w, ok := ctx.Value(middleware.HTTPResponseKey).(http.ResponseWriter); ok {
		r.setRefreshTokenCookie(w, refreshToken)
	}
	return authResp, nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input dto.ChangePasswordRequest) (bool, error) {
	userId, exists := utils.UserIdFromContext(ctx)
	if !exists {
		return false, errors.New("unauthorized")
	}
	v := helper.NewValidator()
	dto.ValidateChangePasswordRequest(v, &input)
	if !v.Valid() {
		return false, helper.NewValidateError(v)
	}

	if err := r.authService.ChangePassword(ctx, userId, &input); err != nil {
		return false, fmt.Errorf("change password error: %w", err)
	}

	return true, nil
}

// ForgotPassword is the resolver for the forgotPassword field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, input dto.ForgotPasswordRequest) (bool, error) {
	v := helper.NewValidator()
	dto.ValidateForgotPasswordRequest(v, &input)
	if !v.Valid() {
		return false, helper.NewValidateError(v)
	}

	if err := r.authService.ForgotPassword(ctx, &input); err != nil {
		return false, fmt.Errorf("forgot password error: %w", err)
	}

	return true, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input dto.ResetPasswordRequest) (bool, error) {
	v := helper.NewValidator()
	dto.ValidateResetPasswordRequest(v, &input)
	if !v.Valid() {
		return false, helper.NewValidateError(v)
	}

	if err := r.authService.ResetPassword(ctx, &input); err != nil {
		return false, fmt.Errorf("reset password error: %w", err)
	}

	return true, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*dto.AuthResponse, error) {
	// Read cookie from injected request
	req, ok := ctx.Value(middleware.HTTPRequestKey).(*http.Request)
	if !ok {
		return nil, errors.New("internal error: no request in context")
	}
	cookie, err := req.Cookie("refresh_token")
	if err != nil {
		return nil, errors.New("refresh token missing")
	}

	authResp, newToken, err := r.authService.RefreshToken(ctx, cookie.Value)
	if err != nil {
		return nil, fmt.Errorf("refresh token error: %w", err)
	}

	// Set new cookie
	if w, ok := ctx.Value(middleware.HTTPResponseKey).(http.ResponseWriter); ok {
		r.setRefreshTokenCookie(w, newToken)
	}
	return authResp, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	req, _ := ctx.Value(middleware.HTTPRequestKey).(*http.Request)
	if req != nil {
		if cookie, err := req.Cookie("refresh_token"); err == nil {
			_ = r.authService.Logout(ctx, cookie.Value)
		}
	}

	if w, ok := ctx.Value(middleware.HTTPResponseKey).(http.ResponseWriter); ok {
		r.clearRefreshTokenCookie(w)
	}
	return true, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input dto.UpdateProfileRequest) (*dto.UserResponse, error) {
	userId, exists := utils.UserIdFromContext(ctx)
	if !exists {
		return nil, errors.New("unauthorized")
	}

	v := helper.NewValidator()
	dto.ValidateUpdateProfileRequest(v, &input)
	if !v.Valid() {
		return nil, helper.NewValidateError(v)
	}

	updatedUser, err := r.userService.UpdateUserProfile(ctx, userId, &input)
	if err != nil {
		return nil, fmt.Errorf("update user error: %w", err)
	}

	return updatedUser, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input dto.CreateCategoryRequest) (*dto.CategoryResponse, error) {
	admin, err := isAdmin(ctx)
	if err != nil {
		return nil, err
	}

	if !admin {
		return nil, errors.New("access denied")
	}

	v := helper.NewValidator()
	dto.ValidateCreateCategoryRequest(v, &input)
	if !v.Valid() {
		return nil, helper.NewValidateError(v)
	}

	category, err := r.categoryService.CreateCategory(ctx, &input)
	if err != nil {
		return nil, fmt.Errorf("create category error: %w", err)
	}

	return category, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input dto.UpdateCategoryRequest) (*dto.CategoryResponse, error) {
	admin, err := isAdmin(ctx)
	if err != nil {
		return nil, err
	}
	if !admin {
		return nil, errors.New("access denied")
	}

	categoryId, err := parseId(id)
	if err != nil {
		return nil, fmt.Errorf("parse category id error: %w", err)
	}

	v := helper.NewValidator()
	dto.ValidateUpdateCategoryRequest(v, &input)
	if !v.Valid() {
		return nil, helper.NewValidateError(v)
	}

	updatedCategory, err := r.categoryService.UpdateCategory(ctx, categoryId, &input)
	if err != nil {
		return nil, fmt.Errorf("update category error: %w", err)
	}

	return updatedCategory, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	admin, err := isAdmin(ctx)
	if err != nil {
		return false, err
	}

	if !admin {
		return false, errors.New("access denied")
	}

	categoryId, err := parseId(id)
	if err != nil {
		return false, fmt.Errorf("parse category id error: %w", err)
	}

	if err := r.categoryService.DeleteCategory(ctx, categoryId); err != nil {
		return false, fmt.Errorf("delete category error: %w", err)
	}

	return true, nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input dto.CreateProductRequest) (*dto.ProductResponse, error) {
	admin, err := isAdmin(ctx)
	if err != nil {
		return nil, err
	}

	if !admin {
		return nil, errors.New("access denied")
	}

	v := helper.NewValidator()
	dto.ValidateCreateProductRequest(v, &input)
	if !v.Valid() {
		return nil, helper.NewValidateError(v)
	}

	product, err := r.productService.CreateProduct(ctx, &input)
	if err != nil {
		return nil, fmt.Errorf("create product error: %w", err)
	}

	return product, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input dto.UpdateProductRequest) (*dto.ProductResponse, error) {
	admin, err := isAdmin(ctx)
	if err != nil {
		return nil, err
	}

	if !admin {
		return nil, errors.New("access denied")
	}

	productId, err := parseId(id)
	if err != nil {
		return nil, fmt.Errorf("parse product id error: %w", err)
	}

	v := helper.NewValidator()
	dto.ValidateUpdateProductRequest(v, &input)
	if !v.Valid() {
		return nil, helper.NewValidateError(v)
	}

	updatedProduct, err := r.productService.UpdateProduct(ctx, productId, &input)
	if err != nil {
		return nil, fmt.Errorf("update product error: %w", err)
	}

	return updatedProduct, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	admin, err := isAdmin(ctx)
	if err != nil {
		return false, err
	}

	if !admin {
		return false, errors.New("access denied")
	}

	productId, err := parseId(id)
	if err != nil {
		return false, fmt.Errorf("parse product id error: %w", err)
	}

	if err := r.productService.DeleteProduct(ctx, productId); err != nil {
		return false, fmt.Errorf("delete product error: %w", err)
	}

	return true, nil
}

// AddToCart is the resolver for the addToCart field.
func (r *mutationResolver) AddToCart(ctx context.Context, input dto.AddToCartRequest) (*dto.CartResponse, error) {
	userId, exists := utils.UserIdFromContext(ctx)
	if !exists {
		return nil, errors.New("unauthorized")
	}

	resp, err := r.cartService.AddToCart(ctx, userId, &input)
	if err != nil {
		return nil, fmt.Errorf("add to cart error: %w", err)
	}

	return resp, nil
}

// UpdateCartItem is the resolver for the updateCartItem field.
func (r *mutationResolver) UpdateCartItem(ctx context.Context, id string, input dto.UpdateCartItemRequest) (*dto.CartResponse, error) {
	userId, exists := utils.UserIdFromContext(ctx)
	if !exists {
		return nil, errors.New("unauthorized")
	}

	itemId, err := parseId(id)
	if err != nil {
		return nil, fmt.Errorf("failed to parse item id: %w", err)
	}

	cart, err := r.cartService.UpdateCartItem(ctx, userId, itemId, &input)
	if err != nil {
		return nil, fmt.Errorf("update cart error: %w", err)
	}

	return cart, nil
}

// RemoveFromCart is the resolver for the removeFromCart field.
func (r *mutationResolver) RemoveFromCart(ctx context.Context, id string) (bool, error) {
	userId, exists := utils.UserIdFromContext(ctx)
	if !exists {
		return false, errors.New("unauthorized")
	}

	cartId, err := parseId(id)
	if err != nil {
		return false, fmt.Errorf("failed to parse cart id: %w", err)
	}

	if err := r.cartService.RemoveFromCart(ctx, userId, cartId); err != nil {
		return false, fmt.Errorf("remove from cart error: %w", err)
	}

	return true, nil
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context) (*dto.OrderResponse, error) {
	userId, exists := utils.UserIdFromContext(ctx)
	if !exists {
		return nil, errors.New("unauthorized")
	}

	order, err := r.orderService.CreateOrder(ctx, userId)
	if err != nil {
		return nil, fmt.Errorf("create order error: %w", err)
	}

	return order, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*dto.UserResponse, error) {
	userId, exists := utils.UserIdFromContext(ctx)
	if !exists {
		return nil, errors.New("unauthorized")
	}

	user, err := r.userService.GetUserProfile(ctx, userId)
	if err != nil {
		return nil, fmt.Errorf("get user error: %w", err)
	}

	return user, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, page *int, limit *int) (*model.ProductConnection, error) {
	p, l := getPagingNumbers(page, limit)
	products, meta, err := r.productService.GetProducts(ctx, p, l)
	if err != nil {
		return nil, fmt.Errorf("get products error: %w", err)
	}

	edges := make([]*model.ProductEdge, len(products))
	for i, product := range products {
		edges[i] = &model.ProductEdge{
			Node: product,
		}
	}

	return &model.ProductConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			Page:       meta.Page,
			Limit:      meta.Limit,
			Total:      int(meta.Total),
			TotalPages: meta.TotalPage,
		},
	}, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*dto.ProductResponse, error) {
	productId, err := parseId(id)
	if err != nil {
		return nil, fmt.Errorf("parse product id error: %w", err)
	}

	product, err := r.productService.GetProductById(ctx, productId)
	if err != nil {
		return nil, fmt.Errorf("get product error: %w", err)
	}

	return product, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*dto.CategoryResponse, error) {
	categories, err := r.categoryService.GetCategories(ctx)
	if err != nil {
		return nil, fmt.Errorf("get categories error: %w", err)
	}
	result := make([]*dto.CategoryResponse, len(categories))
	for i, category := range categories {
		result[i] = category
	}
	return result, nil
}

// Cart is the resolver for the cart field.
func (r *queryResolver) Cart(ctx context.Context) (*dto.CartResponse, error) {
	userId, exists := utils.UserIdFromContext(ctx)
	if !exists {
		return nil, errors.New("unauthorized")
	}

	user, err := r.cartService.GetCart(ctx, userId)
	if err != nil {
		return nil, fmt.Errorf("get cart error: %w", err)
	}

	return user, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, page *int, limit *int) (*model.OrderConnection, error) {
	userId, exists := utils.UserIdFromContext(ctx)
	if !exists {
		return nil, errors.New("unauthorized")
	}

	p, l := getPagingNumbers(page, limit)

	orders, meta, err := r.orderService.GetOrders(ctx, userId, p, l)
	if err != nil {
		return nil, fmt.Errorf("get orders error: %w", err)
	}

	edges := make([]*model.OrderEdge, len(orders))
	for i, order := range orders {
		edges[i] = &model.OrderEdge{
			Node: order,
		}
	}

	return &model.OrderConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			Page:       meta.Page,
			Limit:      meta.Limit,
			Total:      int(meta.Total),
			TotalPages: meta.TotalPage,
		},
	}, nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*dto.OrderResponse, error) {
	userId, exists := utils.UserIdFromContext(ctx)
	if !exists {
		return nil, errors.New("unauthorized")
	}

	orderId, err := parseId(id)
	if err != nil {
		return nil, fmt.Errorf("parse order id error: %w", err)
	}

	order, err := r.orderService.GetOrder(ctx, userId, orderId)
	if err != nil {
		return nil, fmt.Errorf("get order error: %w", err)
	}

	return order, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
