package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/saleh-ghazimoradi/GopherMarket/internal/dto"
)

// UploadProductImage is the resolver for the uploadProductImage field.
func (r *mutationResolver) UploadProductImage(ctx context.Context, productId uint, image graphql.Upload) (*dto.ProductImageResponse, error) {
	admin, err := isAdmin(ctx)
	if err != nil {
		return nil, err
	}
	if !admin {
		return nil, errors.New("access denied")
	}

	url, err := r.uploadService.UploadProductImage(ctx, productId, image.File, image.Filename)
	if err != nil {
		return nil, fmt.Errorf("upload failed: %w", err)
	}

	imageResp, err := r.productService.AddProductImage(ctx, productId, url, image.Filename)
	if err != nil {
		return nil, fmt.Errorf("add product image error: %w", err)
	}

	return imageResp, nil
}
